language: java
jdk:
- oraclejdk8
install: true
script: mvn -q -T2 clean test javadoc:javadoc
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - REPO=git@github.com:srotya/sidewinder-jdbc.git
  directories:
  - "$HOME/.m2"
